from django.urls import path
from . import views

app_name="Hospital"

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_appointments/', views.my_appointments, name='my_appointments'),
    path('my_prescriptions/', views.my_prescriptions, name='my_prescriptions'),
    path('appointment_list/', views.appointment_list, name='appointment_list'),
    path('create_appointment/', views.create_appointment, name='create_appointment'),
    # path('appointment_detail/<int:pk>/', views.AppointmentDetailView.as_view(), name='appointment_detail'),
    path('update_appointment/<int:pk>/', views.update_appointment, name='update_appointment'),
    path('delete_appointment/<int:pk>/', views.delete_appointment, name='delete_appointment'),
    path('patient_list/', views.PatientListView.as_view(), name='patient_list'),
    path('patient_detail/<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('create_patient/', views.create_patient, name='create_patient'),
    path('update_patient/', views.update_patient, name='update_patient'),
    path('delete_patient/', views.delete_patient, name='delete_patient'),
    path('doctor_list/', views.DoctorListView.as_view(), name='doctor_list'),
    path('doctor_detail/<int:pk>/', views.DoctorDetailView.as_view(), name='doctor_detail'),
    path('create_doctor/', views.create_doctor, name='create_doctor'),
    path('update_doctor/', views.update_doctor, name='update_doctor'),
    path('delete_doctor/', views.delete_doctor, name='delete_doctor'),
    path('billing_list/', views.billing_list, name='billing_list'),
    path('create_billing/', views.create_billing, name='create_billing'),
    path('billing_detail/<int:pk>/', views.billing_detail, name='billing_detail'),
    path('update_billing/<int:pk>/', views.update_billing, name='update_billing'),
    path('delete_billing/<int:pk>/', views.delete_billing, name='delete_billing'),
    path('prescription_list/', views.prescription_list, name='prescription_list'),
    path('create_prescription/', views.create_prescription, name='create_prescription'),
    path('prescription_detail/<int:pk>/', views.prescription_detail, name='prescription_detail'),
    path('update_prescription/<int:pk>/', views.update_prescription, name='update_prescription'),
    path('delete_prescription/<int:pk>/', views.delete_prescription, name='delete_prescription'),
    path('inventory_list/', views.inventory_list, name='inventory_list'),
    path('create_inventory/', views.create_inventory, name='create_inventory'),
    path('inventory_detail/<int:pk>/', views.inventory_detail, name='inventory_detail'),
    path('update_inventory/<int:pk>/', views.update_inventory, name='update_inventory'),
    path('delete_inventory/<int:pk>/', views.delete_inventory, name='delete_inventory'),
]
