# Generated by Django 4.1.7 on 2023-04-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
    ]
