# Generated by Django 4.1.7 on 2023-04-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20230404_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_patient', to='Hospital.medical_history'),
        ),
    ]
