# Generated by Django 4.1.7 on 2023-04-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_alter_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='patient',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_history', to='Hospital.patient'),
        ),
    ]
