# Generated by Django 4.1.7 on 2023-04-04 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_alter_administrator_dob_alter_doctor_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_file',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
