# Generated by Django 4.1.7 on 2023-04-04 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_alter_medical_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, help_text='use YYYY-MM-DD format'),
        ),
    ]
