# Generated by Django 4.1.7 on 2023-04-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_alter_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='files', to='Hospital.medical_file'),
        ),
    ]
