# Generated by Django 4.1.7 on 2023-04-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_alter_medical_history_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
