# Generated by Django 4.1.7 on 2023-04-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
