# Generated by Django 4.1.7 on 2023-04-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_alter_administrator_address_alter_doctor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='is_superuser',
        ),
    ]
