# Generated by Django 4.1.7 on 2023-04-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_remove_doctor_is_superuser_remove_nurse_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='gender',
        ),
        migrations.AddField(
            model_name='administrator',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='nurse',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex')], default='', max_length=10),
        ),
    ]
