# Generated by Django 4.1.7 on 2023-04-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_remove_administrator_gender_remove_doctor_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='sex',
        ),
    ]
