# Generated by Django 4.1.7 on 2023-04-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0016_alter_medical_file_medical_history_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_file',
            name='medical_history_files',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_files', to='Hospital.medical_history'),
        ),
    ]
