# Generated by Django 4.1.7 on 2023-04-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0020_alter_administrator_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateOfAdmit',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateOfDischarge',
            field=models.DateTimeField(blank=True, default=None, help_text='use YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
