# Generated by Django 4.1.7 on 2023-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0021_alter_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dateOfAdmit',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dateOfDischarge',
        ),
    ]
