# Generated by Django 4.1.7 on 2023-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0024_administrator_end_time_administrator_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_time', 'patient'), ('appointment_time', 'doctor')},
        ),
    ]
