# Generated by Django 4.1.7 on 2023-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0027_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='isbn_number',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
