# Generated by Django 4.1.7 on 2023-04-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0030_prescription_date_created_prescription_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
    ]
