# Generated by Django 4.1.7 on 2023-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0031_remove_prescription_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.FileField(default=0, upload_to='Precriptions_files'),
            preserve_default=False,
        ),
    ]
