# Generated by Django 4.1.7 on 2023-04-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0033_billing_created_by_billing_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_receipt',
            field=models.FileField(default=0, upload_to='Billing_Receipt_files'),
            preserve_default=False,
        ),
    ]
