# Generated by Django 4.1.7 on 2023-04-07 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hospital', '0034_billing_billing_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_billing', to=settings.AUTH_USER_MODEL),
        ),
    ]
